# SPDX-License-Identifier: GPL-3.0-only

"""Foundational GRASS value objects."""

from grass.core.branches import Branch, HistoryPosition
from grass.core.event_store import InMemoryEventStore
from grass.core.events import (
    CauseRef,
    CommittedTransition,
    Event,
    EventPayload,
    EventToCommit,
    TransitionToCommit,
)
from grass.core.genesis import GenesisError, build_genesis_transition
from grass.core.identifiers import (
    BranchId,
    CorrelationId,
    EntityId,
    EventId,
    RelationId,
    TransitionId,
    WorldDefinitionId,
)
from grass.core.initialization_events import (
    InitializationEventPayloadError,
    SimulationInitializedPayload,
    decode_initialization_event,
)
from grass.core.logical_time import LogicalTime
from grass.core.projections import ProjectionError, project_transition, replay_transitions
from grass.core.provenance import Provenance, ProvenanceSourceRef
from grass.core.references import TransitionRef
from grass.core.replay import CheckpointLoader, StateCheckpoint, replay_branch
from grass.core.state import (
    CognitionState,
    Entity,
    EntityScope,
    ExecutionState,
    ProjectionPosition,
    Relation,
    RelationParticipant,
    ResourceKey,
    ResourceQuantity,
    SimulationState,
    StateVariableKey,
    StateVariableScope,
    WorldScope,
    WorldState,
)
from grass.core.world_definitions import (
    WORLD_DEFINITION_SCHEMA_VERSION,
    InitialConditions,
    InitialEntity,
    InitialRelation,
    InitialResource,
    InitialStateVariable,
    SimulationRunConfig,
    WorldDefinition,
    WorldDefinitionError,
    WorldDefinitionRef,
    WorldVocabulary,
    load_world_definition,
)
from grass.core.world_events import (
    EntityCreatedPayload,
    EntityDeactivatedPayload,
    EntityUpdatedPayload,
    RelationCreatedPayload,
    RelationDeactivatedPayload,
    RelationUpdatedPayload,
    ResourceChangedPayload,
    StateVariableChangedPayload,
    WorldEventPayload,
    WorldEventPayloadError,
    decode_world_event,
)

__all__ = [
    "BranchId",
    "Branch",
    "CauseRef",
    "CheckpointLoader",
    "CognitionState",
    "CommittedTransition",
    "CorrelationId",
    "Entity",
    "EntityCreatedPayload",
    "EntityDeactivatedPayload",
    "EntityId",
    "EntityScope",
    "EntityUpdatedPayload",
    "Event",
    "EventId",
    "EventPayload",
    "EventToCommit",
    "ExecutionState",
    "GenesisError",
    "HistoryPosition",
    "InitialConditions",
    "InitialEntity",
    "InitialRelation",
    "InitialResource",
    "InitialStateVariable",
    "InMemoryEventStore",
    "InitializationEventPayloadError",
    "LogicalTime",
    "ProjectionError",
    "ProjectionPosition",
    "Provenance",
    "ProvenanceSourceRef",
    "Relation",
    "RelationCreatedPayload",
    "RelationDeactivatedPayload",
    "RelationId",
    "RelationParticipant",
    "RelationUpdatedPayload",
    "ResourceChangedPayload",
    "ResourceKey",
    "ResourceQuantity",
    "SimulationState",
    "SimulationInitializedPayload",
    "SimulationRunConfig",
    "StateVariableChangedPayload",
    "StateVariableKey",
    "StateVariableScope",
    "StateCheckpoint",
    "TransitionId",
    "TransitionRef",
    "TransitionToCommit",
    "WorldEventPayloadError",
    "WorldEventPayload",
    "WorldDefinition",
    "WorldDefinitionError",
    "WorldDefinitionId",
    "WorldDefinitionRef",
    "WorldScope",
    "WorldState",
    "WorldVocabulary",
    "WORLD_DEFINITION_SCHEMA_VERSION",
    "build_genesis_transition",
    "decode_initialization_event",
    "decode_world_event",
    "load_world_definition",
    "project_transition",
    "replay_branch",
    "replay_transitions",
]
